import {Platform, StyleSheet} from 'react-native';
import {colors} from 'config/colors';
import {mvs, width} from 'config/metrices';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  imglogo:{
    width: '80%',
    height: mvs(40),
    alignSelf: 'center',
    // marginTop: mvs(25),
  },
  waveimg:{
    width: mvs(30),
    height: mvs(30),
  },
  titleview:{
    width: '70%',
    justifyContent:'flex-start',
    marginTop: mvs(20),
    gap: mvs(10),
    paddingHorizontal: mvs(20),
    alignSelf:'center',
  },
  contentContainerStyle: {
    // marginTop: mvs(10),
  },
  contentContainerStyleNew: {
    flexGrow: 1,
    paddingHorizontal: mvs(20),
    paddingVertical: mvs(10),
    // backgroundColor: colors.white,
    justifyContent: 'flex-start',
    borderRadius: mvs(6),
  },
  input:{
    borderRadius: mvs(40),
    borderColor: colors.borderColor,
    height: mvs(50),
    alignItems: 'center',
  },
  inputContainer: {
    borderRadius: mvs(30),
    // backgroundColor: colors.white,
    borderWidth: 1,
    // borderColor: '#E5E5E5',
    height: mvs(52),
    // marginTop: mvs(12),
  },
  txt: {marginBottom: mvs(10), fontSize: mvs(20)},
  button: {
    width: '100%',
    paddingHorizontal: mvs(20),
    position: 'absolute',
    bottom: 0,
    paddingBottom: mvs(Platform?.OS === 'android' ? 20 : 40),
  },
  googlebutton: {
    width: '48%',
    height: mvs(50),
    backgroundColor: colors.white,
    borderRadius: mvs(10),
    alignItems: 'center',
    justifyContent: 'center',
shadowColor: "#000",
shadowOffset: {
	width: 0,
	height: 2,
},
shadowOpacity: 0.23,
shadowRadius: 2.62,

elevation: 4,
  },
  imagebackground: {
    height: mvs(400),
    width: width,
    position: 'absolute',
  },
  loginlogoview: {
    alignSelf: 'center',
    marginTop: mvs(20),
  },
  lottieview: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboradscrollcontent: {
    paddingHorizontal: mvs(0),
    flexGrow: 0,
    paddingBottom: mvs(150),
  },
  loginmoverstext: {
    marginTop: mvs(10),
    marginBottom: mvs(20),
  },
  forgotpasswordview: {
    alignSelf: 'flex-end',
    marginBottom: mvs(15),
  },
  createaccountview: {
    alignSelf: 'center',
    marginTop: mvs(25),
  },
  signupbuttoncontainer: {
    backgroundColor: colors.bluecolor,
    marginTop: mvs(20),
    borderRadius: mvs(10),
  },
  googlefacebookview: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: mvs(10),
  },
  loginview:{
    justifyContent: 'center',
    alignItems: 'center',
    gap: mvs(10),
    marginTop: mvs(20),
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginHorizontal: mvs(20),
    marginTop: mvs(10),
    marginBottom: mvs(20),
    paddingHorizontal: 0,
  },
  compensationToggleContainer: {
    flexDirection: 'row',
    // justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: mvs(20),
    marginTop: mvs(20),
    marginBottom: mvs(20),
  },
  biddingToggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: mvs(12),
  },
  amountInput: {
    borderRadius: mvs(40),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    height: mvs(50),
    backgroundColor: colors.white,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: mvs(12),
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: mvs(20),
    marginBottom: mvs(8),
  },
  radioCircle: {
    height: mvs(20),
    width: mvs(20),
    borderRadius: mvs(10),
    borderWidth: 2,
    borderColor: colors.helixPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioCircleSelected: {
    borderColor: colors.helixPrimary,
  },
  radioInner: {
    height: mvs(10),
    width: mvs(10),
    borderRadius: mvs(5),
    backgroundColor: colors.helixPrimary,
  },
  customCheckbox: {
    width: mvs(20),
    height: mvs(20),
    borderWidth: 2,
    borderColor: colors.helixPrimary,
    borderRadius: mvs(4),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: mvs(2),
  },
  customCheckboxChecked: {
    backgroundColor: colors.helixPrimary,
    borderColor: colors.helixPrimary,
  },
  largeTextInput: {
    borderRadius: mvs(16),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    backgroundColor: colors.white,
    minHeight: mvs(120),
    paddingHorizontal: mvs(16),
    paddingVertical: mvs(12),
    fontSize: mvs(14),
    color: colors.textColor,
  },
  modalButtonContainer: {
    alignItems: 'center',
    // marginTop: mvs(10),
  },
  searchContainer: {
    marginBottom: mvs(20),
    position: 'relative',
    zIndex: 1000,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: mvs(12),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    paddingHorizontal: mvs(16),
    height: mvs(50),
  },
  searchIcon: {
    marginRight: mvs(12),
  },
  searchInput: {
    flex: 1,
    fontSize: mvs(14),
    color: colors.textColor,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: mvs(55),
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    borderRadius: mvs(12),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    maxHeight: mvs(200),
    zIndex: 1001,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  suggestionItem: {
    paddingHorizontal: mvs(16),
    paddingVertical: mvs(12),
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  selectedContainer: {
    marginTop: mvs(20),
    marginBottom: mvs(20),
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mvs(8),
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: '#E6E8FF',
    backgroundColor:colors.primary,
    borderRadius: mvs(20),
    paddingHorizontal: mvs(12),
    paddingVertical: mvs(6),
    marginRight: mvs(8),
    marginBottom: mvs(8),
  },
  tagClose: {
    marginLeft: mvs(8),
  },
  numberIndicator: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  numberBox: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: mvs(4),
    paddingHorizontal: mvs(8),
    paddingVertical: mvs(4),
    marginBottom: mvs(2),
    minWidth: mvs(30),
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    paddingHorizontal: mvs(20),
    paddingTop: mvs(10),
    paddingBottom: mvs(16),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: mvs(20),
    paddingBottom: mvs(100),
  },
  section: {
    marginBottom: mvs(24),
  },
  sectionTitle: {
    marginBottom: mvs(12),
    textTransform: 'uppercase',
  },
  multilineInput: {
    borderRadius: mvs(16),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    backgroundColor: colors.white,
    minHeight: mvs(120),
    paddingHorizontal: mvs(16),
    paddingVertical: mvs(12),
    fontSize: mvs(14),
    color: colors.textColor,
    textAlignVertical: 'top',
    marginBottom: mvs(8),
  },
  characterCount: {
    marginBottom: mvs(12),
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent:"flex-start",
    alignItems: 'center',
    marginBottom: mvs(20),
  },
  saveButtonContainer: {
    paddingHorizontal: mvs(20),
    paddingBottom: mvs(Platform?.OS === 'android' ? 20 : 40),
    paddingTop: mvs(10),
    // backgroundColor: colors.white,
  },
  saveButton: {
    borderRadius: mvs(25),
    height: mvs(50),
    backgroundColor: colors.primary || '#3A3E90',
    width: '100%',
  },
  attributeSection: {
    marginBottom: mvs(20),
  },
  attributeLabel: {
    marginBottom: mvs(8),
  },
  attributeRow: {
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: mvs(12),
  },
  attributeInput: {
    flex: 1,
    borderRadius: mvs(16),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    height: mvs(50),
    backgroundColor: colors.white,
  },
  instructionText: {
    textAlign: 'center',
    marginTop: mvs(8),
    marginBottom: mvs(20),
  },
  healthSection: {
    marginBottom: mvs(20),
  },
  healthLabel: {
    marginBottom: mvs(12),
  },
  healthRow: {
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: mvs(12),
  },
  healthInput: {
    flex: 1,
    borderRadius: mvs(16),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    height: mvs(50),
    backgroundColor: colors.white,
    paddingHorizontal: mvs(16),
    fontSize: mvs(14),
    color: colors.textColor,
  },
  radioGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  introText: {
    marginTop: mvs(12),
    marginBottom: mvs(20),
    lineHeight: mvs(20),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: mvs(16),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    paddingHorizontal: mvs(16),
    height: mvs(50),
    marginBottom: mvs(24),
  },
  searchIcon: {
    marginRight: mvs(12),
  },
  searchInput: {
    flex: 1,
    fontSize: mvs(14),
    color: colors.textColor,
  },
  conditionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: mvs(8),
    marginBottom: mvs(20),
  },
  conditionTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: mvs(20),
    paddingHorizontal: mvs(12),
    paddingVertical: mvs(8),
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginRight: mvs(8),
    marginBottom: mvs(8),
  },
  conditionTagSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary || '#3A3E90',
    borderRadius: mvs(20),
    paddingHorizontal: mvs(12),
    paddingVertical: mvs(8),
    marginRight: mvs(8),
    marginBottom: mvs(8),
  },
  removeButton: {
    marginLeft: mvs(8),
    padding: mvs(4),
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: mvs(20),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E5E5',
  },
  dividerText: {
    marginHorizontal: mvs(12),
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary || '#3A3E90',
    borderRadius: mvs(40),
    paddingVertical: mvs(16),
    paddingHorizontal: mvs(20),
    gap: mvs(8),
    marginBottom: mvs(20),
  },
  uploadButtonText: {
    marginLeft: mvs(8),
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: mvs(12),
  },
  logoSubtext: {
    marginTop: mvs(4),
    letterSpacing: 0.5,
  },
  descriptionText: {
    marginBottom: mvs(20),
    textAlign: 'center',
    lineHeight: mvs(20),
  },
  getStartedButton: {
    backgroundColor: colors.primary || '#3A3E90',
    borderRadius: mvs(40),
    paddingVertical: mvs(16),
    paddingHorizontal: mvs(20),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: mvs(20),
  },
  sectionValue: {
    marginBottom: mvs(16),
  },
  separator: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginVertical: 0,
  },
  sectionSeparator: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginTop: mvs(20),
    marginBottom: mvs(20),
  },
  bottomButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: mvs(20),
    paddingBottom: mvs(Platform?.OS === 'android' ? 20 : 40),
    paddingTop: mvs(10),
    gap: mvs(12),
  },
  viewBillingButton: {
    flex: 1,
    height: mvs(50),
    borderRadius: mvs(25),
    borderWidth: 1,
    borderColor: colors.primary || '#3A3E90',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  changePlanButton: {
    flex: 1,
    height: mvs(50),
    borderRadius: mvs(25),
    backgroundColor: colors.primary || '#3A3E90',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: mvs(12),
    marginBottom: mvs(4),
  },
  logOutButtonContainer: {
    paddingHorizontal: mvs(20),
    paddingBottom: mvs(Platform?.OS === 'android' ? 20 : 40),
    paddingTop: mvs(10),
    alignItems: 'center',
  },
  logOutButton: {
    width: '100%',
    height: mvs(50),
    borderRadius: mvs(25),
    backgroundColor: colors.primary || '#3A3E90',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: mvs(20),
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: mvs(16),
    padding: mvs(24),
    width: '100%',
    maxWidth: mvs(320),
    alignItems: 'center',
  },
  modalTitle: {
    marginBottom: mvs(12),
    textAlign: 'center',
  },
  modalMessage: {
    marginBottom: mvs(24),
    textAlign: 'center',
    lineHeight: mvs(20),
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    width: '100%',
    gap: mvs(12),
  },
  modalCancelButton: {
    flex: 1,
    height: mvs(44),
    borderRadius: mvs(22),
    borderWidth: 1,
    borderColor: colors.primary || '#3A3E90',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDeleteButton: {
    flex: 1,
    height: mvs(44),
    borderRadius: mvs(22),
    backgroundColor: '#FF5F57',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: mvs(12),
    paddingHorizontal: mvs(16),
    paddingVertical: mvs(12),
    marginBottom: mvs(16),
  },
  notificationItem: {
    position: 'relative',
    paddingVertical: mvs(12),
    minHeight: mvs(50),
  },
  notificationText: {
    lineHeight: mvs(20),
    marginBottom: mvs(4),
    paddingRight: mvs(80),
  },
  notificationTimestamp: {
    position: 'absolute',
    bottom: mvs(12),
    right: 0,
  },
});
export default styles;
